# Generated by Django 3.2.16 on 2023-11-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ttext',
            new_name='text',
        ),
    ]
